[workspace]
authors = ["Awenforever <king_wedo@163.com>"]
channels = ["conda-forge"]
name = "USTCBadminton"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pyside2 = ">=5.15.15,<6"
numpy = ">=2.2.6,<3"
pynput = ">=1.8.1,<2"
pywinauto = ">=0.6.9,<0.7"
pyautogui = ">=0.9.54,<0.10"
pywin32 = ">=311,<312"
opencv = ">=4.12.0,<5"
qt = ">=5.15.15,<6"
rich = ">=14.2.0,<15"
keyboard = ">=0.13.5,<0.14"
